config/routes.rb
Rails.application.routes.draw do
  resources :filters
  devise_for :users
  scope "/admin" do
   resources :users
  end
  get 'deletealljob' => "welcome#cancelalljobs", as: :deletealljobs
  get 'deletejob/:id' => "welcome#canceljob", as: :deletejob
get 'parsedomains/(:websites)' => 'domain#parsedomains' , as: :parsedomains

  get 'loadDomain' => 'scraper#loadDomain'
 post 'domain/domain_index' => 'domain#index'
  post 'scrapedomain' => 'scraper#scrapedomain'
  require 'sidekiq/web'
   mount Sidekiq::Web => '/sidekiq'

   root 'welcome#home'
  resources :domain
  
  

end

app/models/domain.rb
class Domain < ActiveRecord::Base
  
  self.per_page=10
  
  #validates :domainname, presence:true,uniqueness:true
end

app/controllers/domain_controller.rb
class DomainController < ApplicationController
  include Parsedomains
  
  def index
    respond_to do |format|
      format.html
      format.json {render json: DomainDatatable.new(view_context)}
    #@domains=Domain.paginate(:page =>params[:page])
    end
  end
  
  def show
    
    
    @domain =Domain.find(params[:id])
    @filter=Filter.all
    @scraped=loaddomain(@domain)
    @fil=scrape_domains(@domain)
    

  end
  def parsedomains
    if(params['websites'])
      domains=Domain.where(haswebsite: true).count
      haswebsite=true
    else
      domains=Domain.where(scraped: nil,haswebsite: nil).count
      haswebsite=false
    end
    
    i=0
    puts "Domains=#{domains}"  
    while i < domains
      ParsedomainsWorker.perform_async(1000,i,haswebsite)
      i=i+1000
    end
    
    flash[:notice]="Parse Domains Added to Queue Successfully"
    redirect_to root_path
    
  end
  
  
  
  def datatable
    respond_to do |format|
      format.html
      format.json {render :json=> DomainDatatable.new(view_context)}
    end
    
  end
end

app/views/domain/datatable.html.erb
<table id="domains-table", data-source="<%= domains2_path(format: :json) %>">
  
  <thead>
    <tr>
      <th>Domain Name</th>
      <th>Number of Views</th>
    </tr>
  </thead>
</table>

app/views/domain/index.html.erb
<div class="box">
    <div class="box-header with-border">
      <h3 class="box-title">Expiring Domains</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <div class="dataTables_wrapper dt-bootstrap" id="example_wrapper"></div>
      <table class="table table-bordered" id="domains" data-source="<%= domain_domain_index_path(format: "json") %>">
      <thead>
      <tr>
        <th>ID</th>
        <th>Domain Name</th>
        <th>Domain Price</th>
        <th>Number Of Bids</th>
        <th>Domain Valuation</th>
        
        <th>Traffic</th>
        <th>is Adult</th>
        <th>Auction End Time</th>
        <th>Has Website</th>
        <th>Source</th>
        <th>Filter Matched</th>
      </tr>
      </thead>
      <tbody>

    </tbody>
      </table>
      
      <div class="box-footer clearfix">
        Filter Has Websites :
            <select id="haswebsite">
              <option value=''>Has Websites</option>
              <option value="1">True</option>
              <option value="0">False</option>
            </select>
            
            Filter Feed Source :
            <select id="source">
              <option value=''>Feed Source</option>
              <option value="GoDaddy Auctions">Go Daddy Auctions</option>
              <option value="SnapNames">SnapNames</option>
              <option value="CloseOut">CloseOut Domains</option>
            </select>
            
            Filter Domain Ending :
            <select id="domainending">
              <option value=''>Domain Ending</option>
              <option value=".COM">.com</option>
              <option value=".CO.UK">.co.uk</option>
               <option value=".INFO">.info</option>
              <option value=".UK">.uk</option>
              <option value=".NET">.net</option>
              <option value=".ORG">.org</option>
            </select>
            
             Filter Domain Ending :
            <select id="endtime">
              <option value=''>Domain Expire Date</option>
              <option value="today">Today</option>
              <option value="tomorrow">Tomorrow</option>
               <option value="2days">2 days</option>
              <option value="3days">3 Days</option>
              <option value="4days">4 Days</option>
              <option value="5days">5 Days</option>
            </select>
            
            
            </div>
            
            
          </div>
          </div>

app/views/domain/show.html.erb
<section class="invoice">
  
  <div class="row">
    <div class="col-xs-12">
      <h2 class="page-header"><a href="http://www.<%= @domain.domainname %>"><%= @domain.domainname %></a></h2>
    </div>
  </div>
  
  <div class="row">
    <div class="col-xs-3">
      <h2>Domain Details</h2>
      <p>Number of Bids : <%= @domain.numberOfBids %></p>
      <p>Valuation : <%= @domain.valuation %></p>
      <p>Auction Link : <a href="<%= @domain.link %>"><%= @domain.source %></a></p>
      
      <div>
        <h2>Filters</h2>
      
      </div>
    </div>
    
    <div class="col-xs-9">
      <pre><%=@domain.html%></pre>
    </div>
  </div>
</section>