config/routes.rb
Rails.application.routes.draw do
  resources :filters
  devise_for :users
  scope "/admin" do
   resources :users
  end
  get 'deletealljob' => "welcome#cancelalljobs", as: :deletealljobs
  get 'deletejob/:id' => "welcome#canceljob", as: :deletejob
get 'parsedomains/(:websites)' => 'domain#parsedomains' , as: :parsedomains

  get 'loadDomain' => 'scraper#loadDomain'
 post 'domain/domain_index' => 'domain#index'
  post 'scrapedomain' => 'scraper#scrapedomain'
  require 'sidekiq/web'
   mount Sidekiq::Web => '/sidekiq'

   root 'welcome#home'
  resources :domain
  
  

end

app/models/filter.rb
class Filter < ActiveRecord::Base
  attr_accessor :matched
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  before_action :set_filter, only: [:show, :edit, :update, :destroy]

  # GET /filters
  # GET /filters.json
  def index
    @filters = Filter.all
  end

  # GET /filters/1
  # GET /filters/1.json
  def show
  end

  # GET /filters/new
  def new
    @filter = Filter.new
  end

  # GET /filters/1/edit
  def edit
  end

  # POST /filters
  # POST /filters.json
  def create
    @filter = Filter.new(filter_params)

    respond_to do |format|
      if @filter.save
        format.html { redirect_to @filter, notice: 'Filter was successfully created.' }
        format.json { render :show, status: :created, location: @filter }
      else
        format.html { render :new }
        format.json { render json: @filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filters/1
  # PATCH/PUT /filters/1.json
  def update
    respond_to do |format|
      if @filter.update(filter_params)
        format.html { redirect_to @filter, notice: 'Filter was successfully updated.' }
        format.json { render :show, status: :ok, location: @filter }
      else
        format.html { render :edit }
        format.json { render json: @filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filters/1
  # DELETE /filters/1.json
  def destroy
    @filter.destroy
    respond_to do |format|
      format.html { redirect_to filters_url, notice: 'Filter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filter
      @filter = Filter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filter_params
      params.require(:filter).permit(:name, :selector, :regex, :attr)
    end
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/views/filters/_form.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Create Filter</h3>
  </div>
            <!-- /.box-header -->
            <!-- form start -->
            
<%= form_for(@filter) do |f| %>
  <% if @filter.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@filter.errors.count, "error") %> prohibited this filter from being saved:</h2>

    <ul>
      <% @filter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="box-body">
    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :selector %><br>
      <%= f.text_field :selector %>
    </div>
    <div class="form-group">
      <%= f.label :regex %><br>
      <%= f.text_field :regex %>
    </div>
    <div class="form-group">
      <%= f.label :attr %><br>
      <%= f.text_field :attr %>
    </div>
  
  </div>
    <div class="box-footer">
                <%= f.submit %>
              </div>
            </form>
          </div>
<% end %>


<!-- general form elements -->

app/views/filters/edit.html.erb
<h1>Editing Filter</h1>

<%= render 'form' %>

<%= link_to 'Show', @filter %> |
<%= link_to 'Back', filters_path %>

app/views/filters/index.html.erb
<div class="box">
    <div class="box-header with-border">
      <h3 class="box-title">Listing Filters</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Selector</th>
      <th>Regex</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @filters.each do |filter| %>
      <tr>
        <td><%= filter.name %></td>
        <td><%= filter.selector %></td>
        <td><%= filter.regex %></td>
        <td><%= link_to 'Show', filter %></td>
        <td><%= link_to 'Edit', edit_filter_path(filter) %></td>
        <td><%= link_to 'Destroy', filter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Filter', new_filter_path %>

app/views/filters/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', filters_path %>

app/views/filters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @filter.name %>
</p>

<p>
  <strong>Selector:</strong>
  <%= @filter.selector %>
</p>

<p>
  <strong>Regex:</strong>
  <%= @filter.regex %>
</p>

<%= link_to 'Edit', edit_filter_path(@filter) %> |
<%= link_to 'Back', filters_path %>